### ISSUE TITLE
Handle end game state

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-grubs#131]
Currently when the game finishes, nothing happens and errors are spewed in the console. Let's add a state which has the winning team (so that we can reference it from UI later), and either kicks everyone out of the game, or resets to pregame.

**Comment by peter-r-g** [comment]
Resolved in 5901409d5cff6a4f8782f58a48e3e672a83820e6
![image](https://user-images.githubusercontent.com/11802285/188679843-ff535fc8-0f7e-4bab-abae-b0945e091105.png)
