### ISSUE TITLE
Kill boundary should scale with terrain instead of being static

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-grubs#132]
At max terrain scaling, the kill boundary is much too small. We need to scale this to ensure it's the correct size and not killing worms in valid terrain.

(BaseGamemode.Enter() defines this boundary, and GameConfig.TerrainScale should help)

**Comment by imPukes** [comment]
![image](https://user-images.githubusercontent.com/77700466/189717683-936f768f-dca7-4fca-b612-9e49ae2bddef.png)
Not sure of the need to have side barriers? eventually all grubs will fall down to the water level (bottom killzone)

**Comment by peter-r-g** [comment]
Fixed with 801b3c8594b601353b45e965873bb043a54b3983
