### ISSUE TITLE
Improve performance of SubtractLine method for the Csg World

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-grubs#143]
Currently, [SubtractLine](https://github.com/apetavern/sbox-grubs/blob/main/code/Terrain/World.cs#L56) subtracts from the CsgWorld >100 times, when the line could simply be a single, long, rotated subtraction.

You can easily test this out with the gibgun weapon.

**Comment by matekdev** [comment]
I'll throw up a fix to their lib as well if you haven't already
https://github.com/apetavern/sbox-grubs/commit/c19bc1dd756524987466886f1cda7e41993148c1

**Comment by trundler-dev** [comment]
> I'll throw up a fix to their lib as well if you haven't already [c19bc1d](https://github.com/apetavern/sbox-grubs/commit/c19bc1dd756524987466886f1cda7e41993148c1)

Feel free, although I would experiment more with the lib to ensure this is actually something needing fixed. I don't think the library is even updated for pain week yet.
