### ISSUE TITLE
Allow players to choose their own team colour

### ISSUE THREAD

**Issue by trundlr** [apetavern/sbox-grubs#146]
While we will have it hooked up to a fancy UI colour selector in the future, let's set up a console command for player's to set their own team colour.

Currently, a Color is randomly assigned to a player upon initialization.

Considerations:
- Given the current game flow, a player cannot set their color unless the game has already started. Players are not created until the game is moved to the Playing state. If we want players to be able to set their colour in the menu, we may need to attach a component to each client.
- Should we remember a player's preferred colour? Consider game cookies / writing to file.
- We likely want to build the colour from rgb values.

**Comment by matekdev** [comment]
Partially complete, we need to hook up the UI and set up the color on the client component.
