### ISSUE TITLE
Player health UI

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-grubs#150]
We need a user interface that clearly communicates how much health a player has. A player's health is determined by the sum of all the player's Grubs' health.

A Player with 4 Grubs in a game with a max-health of 100 would have 400 max health. If each grub was at 50 health, the player would have 200/400 health.

Below is an example of player health UI from Worms WMD
![image](https://user-images.githubusercontent.com/57276947/218815405-830af360-b59c-4e5c-be70-398d8544edc3.png)

**Comment by matekdev** [comment]
https://github.com/apetavern/sbox-grubs/commit/0146e1b8938ed386b370b3674711906613ff9d73
