### ISSUE TITLE
Set up inventory to only allow weapons to be equipped if their ammo count is not 0

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-grubs#160]
UI:
In the Inventory UI, if a Weapon's Ammo is 0, the InventoryItem panel should be disabled.

Player Inventory:
Perform a check on the Weapon's Ammo before setting the weapon as active that ensures the Ammo is not 0.

**Comment by matekdev** [comment]
Maybe we should private the `Ammo` field in the future? For now, this should be fine
https://github.com/apetavern/sbox-grubs/commit/5901c1ca7f7da49e21889cf731998f97f10a8cc1
