### ISSUE TITLE
Wind Physics

### ISSUE THREAD

**Issue by Jammie3d** [apetavern/sbox-grubs#165]
There should be a random wind direction and intensity per turn, effecting the physics of projectiles.
HUD indication to show wind direction and strength.

Stretch goal:
If possible it would be great if particles could be effected by the wind too, so that they can change dynamically and help communicate to the player. For things like wind wisps, leaves, smoke, burning ashes etc.

**Comment by matekdev** [comment]
Winds physics are in, we should adjust the strength on the bazooka projectiles. We should show some wind particles.
