### ISSUE TITLE
NameTag health should transition downwards

### ISSUE THREAD

**Issue by matekdev** [apetavern/sbox-grubs#166]
Instead of immediately updating to the new value of the health, it should count downwards / transition to the new value.

**Comment by trundler-dev** [comment]
Relevant: https://github.com/apetavern/sbox-grubs/blob/pre-rewrite/code/UI/Gamemode/World/DamageNumber.cs

**Comment by DrewBritt** [comment]
Done https://github.com/apetavern/sbox-grubs/commit/68e8a77ad0b45b56fd21d1733cb6ec1d30c8b12a
