### ISSUE TITLE
Must finish before playtest

### ISSUE THREAD

**Issue by matekdev** [apetavern/sbox-grubs#226]
- [x] Add clothes to grub in main menu, load in their clientside clothes and then change when they select a new piece
- [x] Dress up the grub either in their clientside clothes or their selected clothes from the main menu
- [x] Add a UI transition from Menu -> Game
- [x] If people use duplicate colours, lighten them (We have player icons now, probably isn't needed)
- [x] Add jump & backflip sound effects
- [x] Hookup restart logic again, maybe show the winner, then bring back the main menu?
- [ ] Fix sound issue matt showed in discord
- [x] Backflip sound sounds deeper than jump sound, re-pitch?
- [x] Camera should wait a little longer until the crate has spawned in fully
- [x] Girder makes a splash noise when spawned inside of water
- [x] Add more colours, maybe steam profile pic idea
- [x] Add chat in the main menu
- [x] Arc physics is too fast and is too much affected by wind
- [x] Spawn in sound on crates
...

**Comment by JammieDodgerr** [comment]
- [ ] Add water splash SFX & VFX
- [ ] Communicate grub taking damage - blood/red flash maybe

**Comment by matekdev** [comment]
- [ ] NRE when grabbing crates (only sometimes)
![image](https://user-images.githubusercontent.com/32153021/234718962-72501db9-5e36-45fa-999c-1bb0390d2a63.png)

**Comment by matekdev** [comment]
- [ ] Muzzle needs to be closer to the player on the torch (if you stand next to a wall and use it there will be a thin wall)
- [ ] UI start button is messed on certain resolutions
- [ ] Death of one grub damaging another grub, doesn't wait for second grub to resolve
- [ ] Crate material is not transitioning in for non hosts
- [ ] Active player falls into the void, game doesn't reset
- [ ] Decrease shotgun damage
- [ ] Black name on connect of new clients
- [ ] Add in a teleport sound
- [ ] Larger profile pics
- [ ] Clothing items appear on dead grubs for connecting clients
- [ ] Clamp the camera, don't let it go below the map, or scrolling outwards
- [ ] Allow spaces, numbers, emojis to player name

**Comment by matekdev** [comment]
- [ ] add new screenshots to the gamemode

**Comment by matekdev** [comment]
- [ ] Resolving issues, fire a minigun right before the turn ends. Use a torch and while it is in use fall into the water

**Comment by matekdev** [comment]
- [ ] main menu button still ending up at 2 lines
- [ ] shotgun too much knockback
- [ ] cant rotate girder
- [ ] Minigun doesn't end turn sometimes
- [ ] Camera should stay at explosion for a few seconds
- [ ] Blowtorch uses wrong particle
- [ ] Backflip anim does not work sometimes at higher pings
- [ ] Crosshair persisting after turn

**Comment by matekdev** [comment]
- [ ] Custom cursors

**Comment by matekdev** [comment]
- [ ] Change out water to use shader
- [ ] Clamp the camera, don't let it go below the map, or scrolling outwards

**Comment by matekdev** [comment]
- [ ] Little crown on the winner
- [ ] Maybe wait till we are back in the main menu to regen world, mark initialized in the gamemode system as false until it is finished.

**Comment by matekdev** [comment]
Closing, we should make separate issues for any remaining things.
