### ISSUE TITLE
Add a world panel that shows the active player what type of item was picked up from a crate

### ISSUE THREAD

**Issue by trundlr** [apetavern/sbox-grubs#228]
We can re-use the inventory icons. The panel can be similar to the damage number panel, but we replace the text with the icon for the inventory item picked up. This will keep the player from having to guess what type of item was just added to their inventory.

**Comment by matekdev** [comment]
Done
https://github.com/apetavern/sbox-grubs/commit/e2d14d83ac77d05e436e216d88f6d376eea5d989
