### ISSUE TITLE
Implement the jetpack tool

### ISSUE THREAD

**Issue by trundlr** [apetavern/sbox-grubs#245]
Jetpack will be a good tool to implement as it will challenge the way we handle input. 
- Currently, the player controller uses W/S for aim and A/D for movement. 
- When a jetpack is equipped, a grub should be able to move with WASD through the air. Gravity should still affect them.
- A jetpack has a charge that runs out while W is held down
- The jetpack charge is shown clearly to all players

The jetpack should largely be art-ready. We will have to add a few particles and sound post implementation.

**Comment by ShadowBrian** [comment]
I got most of this done except for the charge level- needs UI work

**Comment by matekdev** [comment]
Finished except for one issue that I currently have assigned to myself.
