### ISSUE TITLE
Implement particle for wind in world

### ISSUE THREAD

**Issue by trundlr** [apetavern/sbox-grubs#246]
The wind particle should randomly be played in the world to show the wind direction and intensity.

**Comment by matekdev** [comment]
We dont have the wind particles, but I improved the UI for it.

**Comment by trundlr** [comment]
Moving to blocked as the particle is not behaving how I would expect it to. Someone else is welcome to take a crack at it.

**Comment by matekdev** [comment]
https://github.com/apetavern/sbox-grubs/commit/5fa6b86d475401e4089e41edd0e9073ce717c6fd
