### ISSUE TITLE
Camera should follow cursor when using a cursor-based weapon like Girder or Teleport

### ISSUE THREAD

**Issue by trundlr** [apetavern/sbox-grubs#250]
Currently the camera continually tries to re-focus on the active grub, but following the mouse makes more sense in this case.

**Comment by matekdev** [comment]
Done, but it doesn't follow the cursor, I feel it is more natural to allow the user to pan the camera.
https://github.com/apetavern/sbox-grubs/commit/fc4dd46740caed5d56959f5ae78797eda28bf92b
