### ISSUE TITLE
Scorch effect from explosions

### ISSUE THREAD

**Issue by Metapyziks** [apetavern/sbox-grubs#255]
I'd be happy to implement a first pass at this, and someone could replace my placeholder textures.
Since you're using shader graphs, I'll need to add some missing nodes first to support this properly.

Result would be a bit like this:

https://github.com/apetavern/sbox-grubs/assets/1110904/4c9d8362-db45-42a6-896a-1758149b359e

**Comment by trundlr** [comment]
This is definitely something we want to add, and you're welcome to go for it. Our main goal for the scorched earth is to have a different scorch material depending on the environment type, however for a first pass, I think just one universal scorch material would be great. However in-depth you feel like going is entirely up to you!

**Comment by trundlr** [comment]
Closing this as per 161bfdfac56419302124386ffd4621e466f44433 and 9fc9a9916bfa31e4b17e8baa6ab17a530faadbed
