### ISSUE TITLE
Rework explosions to have an explosion destruction radius and a damage radius

### ISSUE THREAD

**Issue by trundlr** [apetavern/sbox-grubs#269]
Currently, there is one radius controlling the terrain destruction and damage radius. We can split these up, so we can choose to have the explosion damage grubs beyond the destruction radius. Furthermore, we should investigate using a falloff curve for the damage other than linear.

**Comment by DrewBritt** [comment]
Done https://github.com/apetavern/sbox-grubs/commit/d2f4f08034ff3e29d252d0d3a69959546736546f
