### ISSUE TITLE
Implement weapon unlock delays

### ISSUE THREAD

**Issue by trundlr** [apetavern/sbox-grubs#277]
I will fill this in with more information soon

**Comment by ShadowBrian** [comment]
Potentially link this to the sudden death terrain lowering as it is supposed to happen once a round as well meaning it has to keep track of rounds anyway.

**Comment by trundlr** [comment]
Completed with https://github.com/apetavern/sbox-grubs/commit/b2c494a5216e6fd8a9ec8441be7cd384dfee63ac
