### ISSUE TITLE
Automatically resolve/ground Grubs that have been floating for too long

### ISSUE THREAD

**Issue by trundlr** [apetavern/sbox-grubs#279]
Using a combination of the Grub's velocity and a timer, we can force the grub to ground, which will help it resolve. Furthermore, we can look further into max standable ground angle. In Worms, you can stand pretty much anywhere that's not 90 degrees.

**Comment by dch-GH** [comment]
Fixed by: https://github.com/apetavern/sbox-grubs/pull/290
