### ISSUE TITLE
Game is constantly not resolving anymore

### ISSUE THREAD

**Issue by matekdev** [apetavern/sbox-grubs#301]
There are a bunch of instances where the game doesn't resolve and gets stuck.

1. I've seen a crate drop stop the game from progressing
2. I saw someone torch someone else into the water and get stuck
3. Just the turn ending??

**Comment by matekdev** [comment]
Unable to reproduce, maybe due to a faulty upload? We should try playtesting again...

**Comment by trundlr** [comment]
Added a Log.Warning that will help players report these instances to us.

**Comment by trundlr** [comment]
Resolved by @DrewBritt, nice work!
