### ISSUE TITLE
Rockets phase through grubs on direct hits.

### ISSUE THREAD

**Issue by dch-GH** [apetavern/sbox-grubs#312]
Usually when its at full charge.

**Comment by trundlr** [comment]
I'm curious if this is due to how we are Lerping along segments for the gadget's position.

`Gadget.Position = Vector3.Lerp( currentSegment.StartPos, currentSegment.EndPos, _alpha );`

It's possible the position is simply skipping over the grub entirely.

**Comment by matekdev** [comment]
This is because the rocket does not come out of the gun with a Y value of 0. Therefore the rocket passes the side of the grub. The only issue is that setting the rocket to have a Y position of 0 makes it look like the rocket didn't come out of the bazooka muzzle.

**Comment by matekdev** [comment]
https://github.com/apetavern/sbox-grubs/commit/d5714dd94e8611beb8a116474e8888077860aec4
